### ISSUE TITLE
Publish to npm repository

### ISSUE THREAD

**Issue by whjvenyl** [capacitor-community/safe-area#1]
**Describe the bug**
This module is not yet published to the npm repository.

**Expected behavior**
Published module ion https://www.npmjs.com/.

**Comment by kawazoe** [comment]
@PolymorphiK If you would like to publish this plugin, I also have a fork with an iOS version that I am currently testing. I could PR the changes back into this plugin if you are interested :)

**Comment by PolymorphiK** [comment]
> @PolymorphiK If you would like to publish this plugin, I also have a fork with an iOS version that I am currently testing. I could PR the changes back into this plugin if you are interested :)

Sure! Let’s sync up?

**Comment by kawazoe** [comment]
I already have a PR opened with part of the work that I've done on the iOS side of things.

There's might be more that I can contribute, including some improvements for Android, but it might be a bit complicated. I found your discord through SoDA. If you'd prefer some real-time chat, I can always ping you through there.

**Comment by tafelnl** [comment]
Capacitor 6 support has landed and a release has been published.

See this comment for more info: https://github.com/capacitor-community/safe-area/pull/2#issuecomment-2092723752
