### ISSUE TITLE
[doc] Recommend the standard StatusBar plugin instead of enabling immersive mode on android

### ISSUE THREAD

**Issue by kawazoe** [capacitor-community/safe-area#3]
Not really a bug, but mostly a suggestion. I think we shouldn't recommend people in the readme to enable immersive mode on android themselves when installing this plugin, and instead direct them toward the [StatusBar plugin's documentation](https://capacitorjs.com/docs/apis/status-bar). This will keep code compartmentalized and make sure they don't break compatibility with standard capacitor features.

**Comment by tafelnl** [comment]
It's been removed from the docs.

See this comment for more info: https://github.com/capacitor-community/safe-area/pull/2#issuecomment-2092723752
