### ISSUE TITLE
Status of the Plugin

### ISSUE THREAD

**Issue by oyed** [capacitor-community/safe-area#4]
I've been struggling to get an Android Capacitor app working with insets - I see this plugin hasn't been published or touched in some time. Are there still plans to finish it off?

**Comment by PolymorphiK** [comment]
Hello, apologize for not working in this. I got tied up at work but yes, I will be picking this back up. 

In its current state it does work for Android though it still needs some work for robustness.

**Comment by oyed** [comment]
Awesome stuff! Thanks for getting back to me so quickly :)

I'll close this now and watch the repo - eagerly looking forward to using this
