### ISSUE TITLE
safe"a"area ?

### ISSUE THREAD

**Issue by juliengloria** [capacitor-community/safe-area#5]
Hi the AndroidManifest.xml,
https://github.com/capacitor-community/safe-area/blob/master/example/android/app/src/main/AndroidManifest.xml

The "package" and "android:name is com.capacitorjs.community.plugins.safeAArea.
While is the strings.xml you have "safearea".

Is that normal ?

**Comment by tafelnl** [comment]
Fixed in latest version.

See this comment for more info: https://github.com/capacitor-community/safe-area/pull/2#issuecomment-2092723752
