### ISSUE TITLE
Capacitor 5 compatibility

### ISSUE THREAD

**Issue by chrisweight-elsewhen** [capacitor-community/safe-area#6]
**Is your feature request related to a problem? Please describe.**
Capacitor 5 is now in beta and requires changes to plugin dependencies in order to compile

**Describe the solution you'd like**
An update of the plugin based up on the guide at: https://capacitorjs.com/docs/next/updating/plugins/5-0#android

**Comment by riccardoFasan** [comment]
Sorry but I think this package is no longer supported by 2020

**Comment by mahyarmirrashed** [comment]
What are the alternatives to this? https://github.com/AlwaysLoveme/capacitor-plugin-safe-area is buggy...

**Comment by tafelnl** [comment]
Capacitor 6 support has landed.

See this comment for more info: https://github.com/capacitor-community/safe-area/pull/2#issuecomment-2092723752
