### ISSUE TITLE
App crashes when calling enable

### ISSUE THREAD

**Issue by DanielHaitink** [capacitor-community/safe-area#7]
**Describe the bug**
The whole app crashes when enable is called.

**To Reproduce**
Call `Capacitor.Plugins.SafeArea.enable({
  customColorsForSystemBars: true,
  statusBarColor: '#00000000', // transparent
  statusBarContent: 'light',
  navigationBarColor: '#00000000', // transparent
  navigationBarContent: 'light',
});`

**Expected behavior**
No crash, enables safe areas

**Desktop (please complete the following information):**
Windows 10, chrome, 

**Smartphone (please complete the following information):**
Android 14, Pixel 6a, Capacitor 6, @capacitor-community/safe-area ^6.0.0-alpha.1

**Comment by tafelnl** [comment]
Does this also happen when enabling the plugin by using the config only?

**Comment by lvzhenbo** [comment]
> Does this also happen when enabling the plugin by using the config only?

This works by using the config only, but it raises the question of how I can change the color of the status bar according to the system color (light or dark), which I can't seem to do in the config file.

**Comment by tafelnl** [comment]
You can actually. Check the docs on possible configuration values: https://github.com/capacitor-community/safe-area?tab=readme-ov-file#configuration

I think the crash on calling `.enable` is caused by not using the main thread. I will release a fix soon

**Comment by lvzhenbo** [comment]
Yes that's what I meant, if I could call it in the program I could adjust the color to suit, rather than writing it dead in the config

> You can actually. Check the docs on possible configuration values: [capacitor-community/safe-area#configuration](https://github.com/capacitor-community/safe-area?tab=readme-ov-file#configuration)
> 
> I think the crash on calling `.enable` is caused by not using the main thread. I will release a fix soon

**Comment by aleygues** [comment]
Hi there, thanks for your work @tafelnl.

It seems like this bug is still happening on version [6.0.0-alpha.7](https://www.npmjs.com/package/@capacitor-community/safe-area/v/6.0.0-alpha.7)

Any idea how to work around to change the colors dynamically?
