### ISSUE TITLE
TypeScript error in config object of `enable()`

### ISSUE THREAD

**Issue by frederikheld** [capacitor-community/safe-area#9]
**Describe the bug**
VSCode gives me the following TypeScript error:

```
Object literal may only specify known properties, and 'customColorsForSystemBars' does not exist in type '{ config: Config; }'.ts(2353)
(property) customColorsForSystemBars: boolean
```

**To Reproduce**
Use the code from the usage example in README.md in a TS project

**Expected behavior**
There should be no TS error. So either the typings need to be fixed or the documentation.

**Comment by frederikheld** [comment]
Actually, the docs are wrong. Following the type hints, this is how the could should look like:

```ts
import { SafeArea } from '@capacitor-community/safe-area';

SafeArea.enable({
  customColorsForSystemBars: true,
  statusBarColor: '#00000000', // transparent
  statusBarContent: 'light',
  navigationBarColor: '#00000000', // transparent
  navigationBarContent: 'light',
});
```

**Comment by tafelnl** [comment]
Good catch. I'll update the docs accordingly

**Comment by frederikheld** [comment]
Thanks for fixing this so quickly :-)
